export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_FRIEND = 'FETCH_FRIEND';
export const FETCH_CURRENT_DISPLAYED_GIFT = 'FETCH_CURRENT_DISPLAYED_GIFT';
